### ISSUE TITLE
Splatcraft Sounds not working

### ISSUE THREAD

**Issue by Theoyeah** [Cibernet83/SplatCraft#10]
Everytime i play the mod, nothing from the weapons to everything's sounds play.

Mods:
obfuscate-0.6.3-1.16.5
Splatcraft-3.0.0-1.16.5
OptiFine_1.16.5_HD_U_G8

Log:

[debug.log](https://github.com/splatcraft/splatcraft-forge/files/9908562/debug.log)
[latest.log](https://github.com/splatcraft/splatcraft-forge/files/9908563/latest.log)

**Comment by Octol1ttle** [comment]
Splatoon sound effects are copyrighted material, so the mod does not come bundled with them, as that would make us a target for Nintendo. You can supply your own sounds with a resource pack (see https://github.com/splatcraft/splatcraft-forge/issues/10#issuecomment-1299385719)

**Comment by Theoyeah** [comment]
so how do you get the resource pack ?

**Comment by Ch1216** [comment]
[FQF-splatcraft-04june21.zip](https://github.com/splatcraft/splatcraft-forge/files/9914787/FQF-splatcraft-04june21.zip)

https://discord.com/channels/671749458840518656/726145142372696496/850533550813741086
