### ISSUE TITLE
Inked blocks aren’t transparent in spectator mode

### ISSUE THREAD

**Issue by Ch1216** [Cibernet83/SplatCraft#13]
![feuiasfm'](https://user-images.githubusercontent.com/68875386/213328172-dce3aee0-41b9-4561-b590-ce86e31e39e4.png)

**Comment by Ch1216** [comment]
Still happens in 1.18.2 rc1

**Comment by Cibernet83** [comment]
Fixed in 4.0 with the implementation of World Ink
