### ISSUE TITLE
Squid bumper’s non-ink pixel glow white when in light and glow red when there is no sky light

### ISSUE THREAD

**Issue by Ch1216** [Cibernet83/SplatCraft#19]
White glow when near light
![ssqifna](https://user-images.githubusercontent.com/68875386/213327070-e365db6e-5954-44ff-aef7-504ec79a7e29.png)

Red glow when they have no sky light (not near SUN light)
![freadsionbfa](https://user-images.githubusercontent.com/68875386/213328415-41878d78-76da-4a19-b94a-06c44c00a38a.png)

to note the squid model used to have the same issues in 3.0.0 development

**Comment by Ch1216** [comment]
the squid model was fixed with this [pr](https://github.com/splatcraft/splatcraft-forge/pull/8) so if possible, it would be great if like whatever he did to squid model there could be applied to squid bumpers
if you want to narrow down what commit fixed the bug, it would be great if these commits could be build [this general bugfix commit](https://github.com/splatcraft/splatcraft-forge/commit/237e4e660d4a26773e90285d565d8d1e22fe38e4), [this one that fixes a crash when rendering the squid model](https://github.com/splatcraft/splatcraft-forge/commit/a10b8498c830d4cbb4e84b8d49d2c67ece130db2), and lastly [this one before the pr](https://github.com/splatcraft/splatcraft-forge/commit/ce5195fdbe432b4b88c65b80cdea56d41ded5024) to see if the issue was fixed before the pr

**Comment by Octol1ttle** [comment]
> the squid model was fixed with this https://github.com/splatcraft/splatcraft-forge/pull/8 so if possible, it would be great if like whatever he did to squid model there could be applied to squid bumpers

In that PR, I deleted `PlayerSquidRenderer` because it's functionality is identical to `InkSquidRenderer`. I did not modify either class' code.

To fix *this* issue, https://github.com/splatcraft/splatcraft-forge/blob/forge/1.16.5/src/main/java/net/splatcraft/forge/client/renderer/SquidBumperRenderer.java and/or https://github.com/splatcraft/splatcraft-forge/blob/forge/1.16.5/src/main/java/net/splatcraft/forge/client/model/SquidBumperModel.java need to be reviewed

**Comment by dvitski** [comment]
Is it possible that the light level is somehow affecting the overlay texture (which controls the hurt time red overlay)?

I can't access source right now but it may be `getPackedLightCoords` in the calculation for the overlay value (`i`).

https://github.com/splatcraft/splatcraft-forge/blob/6350dd53d97d92436b846e40835f05b6f8f9f09e/src/main/java/net/splatcraft/forge/client/renderer/SquidBumperRenderer.java#L124-L127
