### ISSUE TITLE
Tags Crash

### ISSUE THREAD

**Issue by WenXin20** [Cibernet83/SplatCraft#2]
`Minecraft v1.16.4`
`Forge v35.1.28`
`Splatcraft v2.3.0-alpha`

My game crashed client-side as I was trying to join my server.
[Crash Report](https://gist.github.com/WenXin20/6f366695007dcc575bed7809a9cc4914)

**Comment by dvitski** [comment]
Fixed in [`878abb1`](https://github.com/Cibernet83/Splatcraft/commit/878abb10c48464340a289f5b1a50d8f4f841db9c) for next alpha
