### ISSUE TITLE
Inked block rendering issues with shaders enabled

### ISSUE THREAD

**Issue by Theoyeah** [Cibernet83/SplatCraft#23]
I tried using differents shaders and i get the same result, i tried various things but no change, even's optifine default shader have this bug ):
![image](https://user-images.githubusercontent.com/97792861/218312688-f054e5a1-4fd7-460f-a793-493084e7e158.png)
![image](https://user-images.githubusercontent.com/97792861/218312695-8f3a9b8f-4b53-4f29-a349-ed021c742392.png)

**Comment by Octol1ttle** [comment]
Tried using Oculus with BSL, encountered this issue but edges were fully opaque instead of transparent

**Comment by Ch1216** [comment]
have you try using oculus?

**Comment by Theoyeah** [comment]
> have you try using oculus?
yes

**Comment by Theoyeah** [comment]
also btw this was after the 3.0 released, back before the update it still worked

**Comment by Theoyeah** [comment]
> also btw this was after the 3.0 released, back before the update it still worked

i kind of updated due to the bomb feature being added, idk but i think a change between 3.0 and 2.0 caused the bug

**Comment by Theoyeah** [comment]
With the new beta for 1.18.2. I tried playing splatcraft with oculus and Complementary Unbound. Seems to work well with no issues.
