### ISSUE TITLE
Splatcraft unable to compile

### ISSUE THREAD

**Issue by RealRTTV** [Cibernet83/SplatCraft#4]
Basically I've done all the testing already so I'll try to keep it short. In this commit: https://github.com/splatcraft/splatcraft/commit/435a39d7c789862a5367a3e7530ca817a4a28bd8 there was a system implemented to add squid passable tags (I'd assume for map makers) this makes it unable to compile (I've tried to compile the previous commit: https://github.com/splatcraft/splatcraft/commit/af16c377088ad9c3d7bf2d659d8f2b08d7af9c09 and it worked) now I have found two solutions, Solution A: Revert the changes from commit https://github.com/splatcraft/splatcraft/commit/435a39d7c789862a5367a3e7530ca817a4a28bd8 to contents of https://github.com/splatcraft/splatcraft/commit/af16c377088ad9c3d7bf2d659d8f2b08d7af9c09 commit on your newest commit or Option B: Find out why
```
C:\Users\RTTV\Desktop\splatcraft-forge-major-updates\src\main\java\com\cibernet\splatcraft\blocks\GrateBlock.java:25: error: cannot find symbol
public class GrateBlock extends AbstractSquidPassthroughBlock implements IWaterLoggable
                                ^
  symbol: class AbstractSquidPassthroughBlock
C:\Users\RTTV\Desktop\splatcraft-forge-major-updates\src\main\java\com\cibernet\splatcraft\blocks\GrateBlock.java:29: error: cannot find symbol
    public static final Properties PROPERTIES = Properties.create(Material.IRON).notSolid().setRequiresTool().harvestTool(ToolType.PICKAXE).hardnessAndResistance(4.0f).sound(SoundType.METAL);
                        ^
  symbol:   class Properties
  location: class GrateBlock
C:\Users\RTTV\Desktop\splatcraft-forge-major-updates\src\main\java\com\cibernet\splatcraft\blocks\GrateRampBlock.java:24: error: cannot find symbol
public class GrateRampBlock extends AbstractSquidPassthroughBlock implements IWaterLoggable
                                    ^
  symbol: class AbstractSquidPassthroughBlock
```
is happening and fix it

**Comment by dvitski** [comment]
fixed in [`44a8a79`](https://github.com/splatcraft/splatcraft/commit/44a8a79edfa5f39f978c192af96790495dcad77f)
